services:
  app:
    platform: linux/amd64
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGODB_URL: ${MONGODB_URL}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      MAIL_FROM: ${MAIL_FROM}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
